### ISSUE TITLE
can't be run in windows system

### ISSUE THREAD

**Issue by xnetsc** [luapower/mmap#4]
can't be run in windows system for no run-time function about FILE_.
Functions about FILE or FILE_ is supported by msvc compiler in source level,not run-time level.

**Comment by capr** [comment]
I'm not sure I understand this comment. Can you elaborate? I develop this library on Windows, so I'm pretty sure it runs on it.

**Comment by xnetsc** [comment]
_FILE_ is a source level macro means it's only a macro,not a variable or constant when your program is runing……you should know what means 'macro' and what means 'constant'

**Comment by capr** [comment]
Ok, and what's that got to do with this project?

**Comment by xnetsc** [comment]
Actually,you want get the source file name by use '_FILE_'，but for _FILE is only a macro,here you just get the string '_FILE_'……that's the result

**Comment by capr** [comment]
Are you sure you've posted the issue on the right project? This project does not have any C code in it and there's no occurrence of FILE_ anywhere in the code.

**Comment by xnetsc** [comment]
i post it from luapower

**Comment by capr** [comment]
What did you tried exactly and what failed and with what error?
